### ISSUE TITLE
Revise and fix indentation of the code

### ISSUE THREAD

**Issue by fedorov** [millerjv/PkModeling#40]
It appears that indentation is inconsistent at some places.

As an example: https://github.com/millerjv/PkModeling/blob/master/PkSolver/PkSolver.h#L64-L68

This needs to be cleaned up.

**Comment by fedorov** [comment]
while working on this, let's make sure:
* 2 spaces is used for indentation
* soft tabs (tabs should be replaced with 2 spaces)

**Comment by jcfr** [comment]
@fedorov  Look like this can be closed.
