### ISSUE TITLE
PK Extension not building in Slicer 4.10.2 Release

### ISSUE THREAD

**Issue by mec640** [millerjv/PkModeling#71]
Hi, 

Just wondering when an update for this module will be completed for version 4.10.2?

Updated the version last week to find the module is no longer available in the extension manager and really hopeful its not too far away- currently primarily using Slicer for my DCE image analysis. 

Cheers,
Maddie

**Comment by fedorov** [comment]
Per discussion here https://discourse.slicer.org/t/pk-modelling-module-extension-missing/7803/7, it is building for stable, but not for release.
